image:
  file: .gitpod.Dockerfile
ports:
  - port: 9000
    onOpen: open-preview
tasks:
  - name: Server
    init: npm i && gatsby build
    command: gatsby serve
  - name: Terminal
    command: echo ''
vscode:
  extensions:
    - burkeholland.simple-react-snippets@1.2.2:aB/gV0ExPn8v6vEZNUjoWA==
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
    addLabel: ready-to-code
