image:
  file: .gitpod.Dockerfile
ports:
  - port: 8000
    onOpen: open-preview
tasks:
  - init: make deps && make format
    command: python3 app.py
    name: split
  - command: echo split
    openMode: split-right
