image:
  file: .gitpod.Dockerfile
ports:
  - port: 8000
    onOpen: open-preview
tasks:
  - init: cargo build --release
    command: cargo run
  - command: echo split
    openMode: split-right
    name: split
vscode:
  extensions:
    - hashicorp.terraform@2.0.2:tz2tPxgWt4OX2uW4tYxxyA==